# Generated by Django 5.1.3 on 2024-11-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='edad',
            field=models.CharField(max_length=50),
        ),
    ]
