# Generated by Django 5.1.3 on 2024-11-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_alter_publicacion_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='ultima_pipeta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
