# Generated by Django 5.1.3 on 2024-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_publicacion_ultima_pipeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='ultima_vacuna',
            field=models.DateField(default='2024-10-02'),
            preserve_default=False,
        ),
    ]
