# Generated by Django 5.1.3 on 2024-11-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0005_publicacion_ultima_vacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='duracion_pipeta',
            field=models.CharField(choices=[('1', '1 mes'), ('3', '3 meses'), ('no', 'No ha sido suministrado')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado_vacuna',
            field=models.CharField(choices=[('1', 'Vacuna de 1 año'), ('no', 'No ha sido suministrado')], default='no', max_length=10),
        ),
    ]
